apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go19824
  janus-idp.io/tekton: go19824
  backstage.io/kubernetes-id: go19824
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go19824
resources:
- deployment.yaml
- route.yaml
- service.yaml
